export interface Product {
  id: number;
  name: string;
  description: string;
  price: string;
  image: string;
  category: 'NAM' | 'NỮ' | 'TRẺ EM' | 'PHỤ KIỆN' | 'BESTSELLER';
  fullDescription?: string;
  features?: string[];
  sizes?: string[];
}

export const allProducts: Product[] = [
  { id: 1, name: 'Dây kéo cơ thép', description: 'Chất liệu thép bền bỉ', price: '450.000đ', image: 'https://images.pexels.com/photos/3912952/pexels-photo-3912952.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'NAM', fullDescription: 'Dây kéo cơ thép cao cấp được thiết kế cho các bài tập cơ lưng và vai. Chất liệu thép không gỉ đảm bảo độ bền cao và an toàn khi sử dụng.', features: ['Chất liệu thép không gỉ', 'Tay cầm bọc cao su chống trơn', 'Trọng lượng phù hợp mọi cấp độ'], sizes: ['Standard'] },
  { id: 2, name: 'Găng tay GYM', description: 'Chống trơn, bảo vệ tay', price: '250.000đ', image: 'https://images.pexels.com/photos/3838389/pexels-photo-3838389.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'PHỤ KIỆN', fullDescription: 'Găng tay tập gym chuyên dụng với thiết kế chống trơn trượt, bảo vệ bàn tay khỏi vết chai và phồng rộp khi tập luyện.', features: ['Vải thấm mồ hôi cao cấp', 'Lớp đệm bảo vệ lòng bàn tay', 'Dây quấn cổ tay chắc chắn'], sizes: ['M', 'L', 'XL'] },
  { id: 3, name: 'Dây cáp thép', description: 'Mạnh mẽ, đa năng', price: '380.000đ', image: 'https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'BESTSELLER', fullDescription: 'Dây cáp thép đa năng có thể sử dụng cho nhiều bài tập khác nhau, từ tập lưng, tập vai đến tập tay.', features: ['Cáp thép bền chắc', 'Có thể điều chỉnh độ dài', 'Tay cầm ergonomic'], sizes: ['Standard'] },
  { id: 4, name: 'Dây thun tập lưng', description: 'Đàn hồi cao, bền', price: '320.000đ', image: 'https://images.pexels.com/photos/6456225/pexels-photo-6456225.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'NỮ', fullDescription: 'Dây thun kháng lực chất lượng cao với độ đàn hồi tốt, phù hợp cho tập lưng và các bài tập toàn thân.', features: ['Latex tự nhiên đàn hồi cao', 'Không biến dạng sau thời gian dài', '3 mức độ kháng lực'], sizes: ['Light', 'Medium', 'Heavy'] },
  { id: 5, name: 'Dây kéo co giãn', description: 'Đa cấp độ kháng lực', price: '420.000đ', image: 'https://images.pexels.com/photos/4162485/pexels-photo-4162485.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'BESTSELLER', fullDescription: 'Bộ dây kéo co giãn với nhiều mức độ kháng lực khác nhau, giúp bạn tùy chỉnh cường độ tập luyện.', features: ['5 cấp độ kháng lực', 'Có thể kết hợp nhiều dây', 'Túi đựng tiện lợi'], sizes: ['Set'] },
  { id: 6, name: 'Bộ tạ điều chỉnh', description: 'Từ 2.5kg - 24kg', price: '1.250.000đ', image: 'https://images.pexels.com/photos/4162491/pexels-photo-4162491.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'NAM', fullDescription: 'Bộ tạ điều chỉnh thông minh, cho phép thay đổi trọng lượng dễ dàng từ 2.5kg đến 24kg chỉ với một động tác.', features: ['Điều chỉnh nhanh chóng', 'Tiết kiệm không gian', 'Chất liệu gang cao cấp'], sizes: ['2.5-24kg'] },
  { id: 7, name: 'Dây kháng lực', description: 'Phù hợp mọi cấp độ', price: '290.000đ', image: 'https://images.pexels.com/photos/4162487/pexels-photo-4162487.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'PHỤ KIỆN', fullDescription: 'Dây kháng lực đa năng, phù hợp cho người mới bắt đầu đến vận động viên chuyên nghiệp.', features: ['Dễ sử dụng', 'Bền bỉ với thời gian', 'Nhiều màu sắc'], sizes: ['Light', 'Medium', 'Heavy'] },
  { id: 8, name: 'Dây thun tập vai', description: 'Tăng cường cơ vai', price: '350.000đ', image: 'https://images.pexels.com/photos/4162451/pexels-photo-4162451.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'NỮ', fullDescription: 'Dây thun chuyên dụng cho các bài tập vai, giúp phát triển và định hình bờ vai đẹp.', features: ['Thiết kế ergonomic', 'Tập trung vào cơ vai', 'Chất liệu cao su bền'], sizes: ['Standard'] },
  { id: 9, name: 'Thảm tập Yoga', description: 'Chống trơn, êm ái', price: '380.000đ', image: 'https://images.pexels.com/photos/4056723/pexels-photo-4056723.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'NỮ', fullDescription: 'Thảm yoga cao cấp với bề mặt chống trơn và độ dày vừa phải, mang lại sự thoải mái tối đa khi tập.', features: ['Dày 6mm êm ái', 'Bề mặt chống trơn 2 mặt', 'Túi đựng và dây đeo'], sizes: ['173cm x 61cm'] },
  { id: 10, name: 'Bóng tập thể dục', description: 'Size 65cm, chống nổ', price: '420.000đ', image: 'https://images.pexels.com/photos/3757376/pexels-photo-3757376.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'BESTSELLER', fullDescription: 'Bóng tập thể dục với công nghệ chống nổ an toàn, phù hợp cho các bài tập core và pilates.', features: ['Công nghệ chống nổ', 'Chịu tải 300kg', 'Bơm kèm theo'], sizes: ['55cm', '65cm', '75cm'] },
  { id: 11, name: 'Bình nước Gym', description: 'Dung tích 1L, không BPA', price: '150.000đ', image: 'https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'PHỤ KIỆN', fullDescription: 'Bình nước thể thao cao cấp, không chứa BPA, an toàn cho sức khỏe với dung tích 1 lít.', features: ['Nhựa không BPA', 'Nắp kín chống tràn', 'Dễ vệ sinh'], sizes: ['1L'] },
  { id: 12, name: 'Đai lưng tập gym', description: 'Hỗ trợ lưng tốt', price: '550.000đ', image: 'https://images.pexels.com/photos/3837757/pexels-photo-3837757.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'NAM', fullDescription: 'Đai lưng hỗ trợ chuyên dụng cho tập luyện với tạ nặng, bảo vệ cột sống và giảm nguy cơ chấn thương.', features: ['Vải dày chắc chắn', 'Khóa đai kim loại bền', 'Đệm lưng hỗ trợ'], sizes: ['S', 'M', 'L', 'XL'] },
  { id: 13, name: 'Tạ tay 5kg', description: 'Bọc cao su chống trơn', price: '480.000đ', image: 'https://images.pexels.com/photos/3837781/pexels-photo-3837781.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'NAM', fullDescription: 'Tạ tay bọc cao su cao cấp, thiết kế chống trơn và bảo vệ sàn nhà khi đặt xuống.', features: ['Bọc cao su dày', 'Cầm nắm thoải mái', 'Trọng lượng chuẩn'], sizes: ['5kg'] },
  { id: 14, name: 'Dây nhảy thể dục', description: 'Nhẹ, xoay trơn tru', price: '180.000đ', image: 'https://images.pexels.com/photos/4162485/pexels-photo-4162485.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'TRẺ EM', fullDescription: 'Dây nhảy tốc độ cao với vòng bi xoay mượt mà, lý tưởng cho cardio và giảm cân.', features: ['Vòng bi xoay 360 độ', 'Dây cáp thép bọc nhựa', 'Điều chỉnh độ dài'], sizes: ['Adjustable'] },
  { id: 15, name: 'Băng quấn tay', description: 'Hấp thụ mồ hôi tốt', price: '120.000đ', image: 'https://images.pexels.com/photos/3838389/pexels-photo-3838389.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'PHỤ KIỆN', fullDescription: 'Băng quấn tay thể thao thấm hút mồ hôi hiệu quả, giữ cho cổ tay và bàn tay luôn khô ráo.', features: ['Vải cotton thấm hút', 'Co giãn tốt', 'Giặt máy được'], sizes: ['One Size'] },
  { id: 16, name: 'Xà đơn treo tường', description: 'Chịu lực 150kg', price: '680.000đ', image: 'https://images.pexels.com/photos/4162451/pexels-photo-4162451.jpeg?auto=compress&cs=tinysrgb&w=800', category: 'NAM', fullDescription: 'Xà đơn treo tường chắc chắn, lắp đặt dễ dàng, chịu lực tối đa 150kg, phù hợp tập tại nhà.', features: ['Thép carbon chịu lực cao', 'Lắp đặt đơn giản', 'Nhiều vị trí cầm'], sizes: ['Standard'] },
];
